---
- hosts: linux
  ignore_errors: true
  tasks:
  - name:  print command output
    command:
      ls - l test.txt
    register: log
  - debug: msg="standard output={{log.stdout}}"
  - debug: msg="standard error={{log.stderr}}" 
